// NOTE: YOU SHOULD NOT BE USING THIS FILE.
// This is a saved version of a moc file generated by Qt Creator. It only exists for debugging in Visual Studio.
// This file is most likely out of data and will need to be replaced with a freshly-generated version every
// time you want to debug in Visual Studio.
//
// Compiling actual shippable code should be done in Qt Creator, not Visual Studio

/****************************************************************************
** Meta object code from reading C++ file 'VorbitalDlg.h'
**
** Created by: The Qt Meta Object Compiler version 67 (Qt 5.7.0)
**
** WARNING! All changes made in this file will be lost!
*****************************************************************************/

#include "VorbitalDlg.h"
#include <QtCore/qbytearray.h>
#include <QtCore/qmetatype.h>
#if !defined(Q_MOC_OUTPUT_REVISION)
#error "The header file 'VorbitalDlg.h' doesn't include <QObject>."
#elif Q_MOC_OUTPUT_REVISION != 67
#error "This file was generated using the moc from 5.7.0. It"
#error "cannot be used with the include files from this version of Qt."
#error "(The moc has changed too much.)"
#endif

QT_BEGIN_MOC_NAMESPACE
struct qt_meta_stringdata_VorbitalDlg_t {
    QByteArrayData data[40];
    char stringdata0[550];
};
#define QT_MOC_LITERAL(idx, ofs, len) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    qptrdiff(offsetof(qt_meta_stringdata_VorbitalDlg_t, stringdata0) + ofs \
        - idx * sizeof(QByteArrayData)) \
    )
static const qt_meta_stringdata_VorbitalDlg_t qt_meta_stringdata_VorbitalDlg = {
    {
QT_MOC_LITERAL(0, 0, 11), // "VorbitalDlg"
QT_MOC_LITERAL(1, 12, 18), // "numchannelsChanged"
QT_MOC_LITERAL(2, 31, 0), // ""
QT_MOC_LITERAL(3, 32, 8), // "channels"
QT_MOC_LITERAL(4, 41, 14), // "bitrateChanged"
QT_MOC_LITERAL(5, 56, 7), // "bitrate"
QT_MOC_LITERAL(6, 64, 15), // "bitdepthChanged"
QT_MOC_LITERAL(7, 80, 8), // "bitdepth"
QT_MOC_LITERAL(8, 89, 17), // "samplerateChanged"
QT_MOC_LITERAL(9, 107, 10), // "samplerate"
QT_MOC_LITERAL(10, 118, 11), // "timeChanged"
QT_MOC_LITERAL(11, 130, 4), // "time"
QT_MOC_LITERAL(12, 135, 13), // "volumeChanged"
QT_MOC_LITERAL(13, 149, 6), // "volume"
QT_MOC_LITERAL(14, 156, 15), // "albumArtChanged"
QT_MOC_LITERAL(15, 172, 8), // "filename"
QT_MOC_LITERAL(16, 181, 21), // "OnPlaylistDoubleClick"
QT_MOC_LITERAL(17, 203, 16), // "QListWidgetItem*"
QT_MOC_LITERAL(18, 220, 4), // "item"
QT_MOC_LITERAL(19, 225, 13), // "OnNumChannels"
QT_MOC_LITERAL(20, 239, 5), // "value"
QT_MOC_LITERAL(21, 245, 9), // "OnBitrate"
QT_MOC_LITERAL(22, 255, 12), // "OnSampleRate"
QT_MOC_LITERAL(23, 268, 4), // "rate"
QT_MOC_LITERAL(24, 273, 6), // "OnTime"
QT_MOC_LITERAL(25, 280, 7), // "seconds"
QT_MOC_LITERAL(26, 288, 19), // "OnButtonBrowseClick"
QT_MOC_LITERAL(27, 308, 25), // "OnButtonBrowseFolderClick"
QT_MOC_LITERAL(28, 334, 17), // "OnButtonPlayClick"
QT_MOC_LITERAL(29, 352, 17), // "OnButtonStopClick"
QT_MOC_LITERAL(30, 370, 20), // "OnButtonForwardClick"
QT_MOC_LITERAL(31, 391, 20), // "OnButtonReverseClick"
QT_MOC_LITERAL(32, 412, 18), // "OnButtonPauseClick"
QT_MOC_LITERAL(33, 431, 19), // "OnButtonRemoveClick"
QT_MOC_LITERAL(34, 451, 21), // "OnButtonSettingsClick"
QT_MOC_LITERAL(35, 473, 18), // "OnButtonClearClick"
QT_MOC_LITERAL(36, 492, 22), // "OnButtonRandomizeClick"
QT_MOC_LITERAL(37, 515, 7), // "OnAbout"
QT_MOC_LITERAL(38, 523, 8), // "OnVolume"
QT_MOC_LITERAL(39, 532, 17) // "OnAlbumArtChanged"

    },
    "VorbitalDlg\0numchannelsChanged\0\0"
    "channels\0bitrateChanged\0bitrate\0"
    "bitdepthChanged\0bitdepth\0samplerateChanged\0"
    "samplerate\0timeChanged\0time\0volumeChanged\0"
    "volume\0albumArtChanged\0filename\0"
    "OnPlaylistDoubleClick\0QListWidgetItem*\0"
    "item\0OnNumChannels\0value\0OnBitrate\0"
    "OnSampleRate\0rate\0OnTime\0seconds\0"
    "OnButtonBrowseClick\0OnButtonBrowseFolderClick\0"
    "OnButtonPlayClick\0OnButtonStopClick\0"
    "OnButtonForwardClick\0OnButtonReverseClick\0"
    "OnButtonPauseClick\0OnButtonRemoveClick\0"
    "OnButtonSettingsClick\0OnButtonClearClick\0"
    "OnButtonRandomizeClick\0OnAbout\0OnVolume\0"
    "OnAlbumArtChanged"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_VorbitalDlg[] = {

 // content:
       7,       // revision
       0,       // classname
       0,    0, // classinfo
      26,   14, // methods
       0,    0, // properties
       0,    0, // enums/sets
       0,    0, // constructors
       0,       // flags
       7,       // signalCount

 // signals: name, argc, parameters, tag, flags
       1,    1,  144,    2, 0x06 /* Public */,
       4,    1,  147,    2, 0x06 /* Public */,
       6,    1,  150,    2, 0x06 /* Public */,
       8,    1,  153,    2, 0x06 /* Public */,
      10,    1,  156,    2, 0x06 /* Public */,
      12,    1,  159,    2, 0x06 /* Public */,
      14,    1,  162,    2, 0x06 /* Public */,

 // slots: name, argc, parameters, tag, flags
      16,    1,  165,    2, 0x0a /* Public */,
      19,    1,  168,    2, 0x0a /* Public */,
      21,    1,  171,    2, 0x0a /* Public */,
      22,    1,  174,    2, 0x0a /* Public */,
      24,    1,  177,    2, 0x0a /* Public */,
      26,    0,  180,    2, 0x0a /* Public */,
      27,    0,  181,    2, 0x0a /* Public */,
      28,    0,  182,    2, 0x0a /* Public */,
      29,    0,  183,    2, 0x0a /* Public */,
      30,    0,  184,    2, 0x0a /* Public */,
      31,    0,  185,    2, 0x0a /* Public */,
      32,    0,  186,    2, 0x0a /* Public */,
      33,    0,  187,    2, 0x0a /* Public */,
      34,    0,  188,    2, 0x0a /* Public */,
      35,    0,  189,    2, 0x0a /* Public */,
      36,    0,  190,    2, 0x0a /* Public */,
      37,    0,  191,    2, 0x0a /* Public */,
      38,    1,  192,    2, 0x0a /* Public */,
      39,    1,  195,    2, 0x0a /* Public */,

 // signals: parameters
    QMetaType::Void, QMetaType::Int,    3,
    QMetaType::Void, QMetaType::Int,    5,
    QMetaType::Void, QMetaType::Int,    7,
    QMetaType::Void, QMetaType::Int,    9,
    QMetaType::Void, QMetaType::Int,   11,
    QMetaType::Void, QMetaType::Int,   13,
    QMetaType::Void, QMetaType::QString,   15,

 // slots: parameters
    QMetaType::Void, 0x80000000 | 17,   18,
    QMetaType::Void, QMetaType::Int,   20,
    QMetaType::Void, QMetaType::Int,    5,
    QMetaType::Void, QMetaType::Int,   23,
    QMetaType::Void, QMetaType::Int,   25,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int,   20,
    QMetaType::Void, QMetaType::QString,   15,

       0        // eod
};

void VorbitalDlg::qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
{
    if (_c == QMetaObject::InvokeMetaMethod) {
        VorbitalDlg *_t = static_cast<VorbitalDlg *>(_o);
        Q_UNUSED(_t)
        switch (_id) {
        case 0: _t->numchannelsChanged((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 1: _t->bitrateChanged((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 2: _t->bitdepthChanged((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 3: _t->samplerateChanged((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 4: _t->timeChanged((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 5: _t->volumeChanged((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 6: _t->albumArtChanged((*reinterpret_cast< const QString(*)>(_a[1]))); break;
        case 7: _t->OnPlaylistDoubleClick((*reinterpret_cast< QListWidgetItem*(*)>(_a[1]))); break;
        case 8: _t->OnNumChannels((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 9: _t->OnBitrate((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 10: _t->OnSampleRate((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 11: _t->OnTime((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 12: _t->OnButtonBrowseClick(); break;
        case 13: _t->OnButtonBrowseFolderClick(); break;
        case 14: _t->OnButtonPlayClick(); break;
        case 15: _t->OnButtonStopClick(); break;
        case 16: _t->OnButtonForwardClick(); break;
        case 17: _t->OnButtonReverseClick(); break;
        case 18: _t->OnButtonPauseClick(); break;
        case 19: _t->OnButtonRemoveClick(); break;
        case 20: _t->OnButtonSettingsClick(); break;
        case 21: _t->OnButtonClearClick(); break;
        case 22: _t->OnButtonRandomizeClick(); break;
        case 23: _t->OnAbout(); break;
        case 24: _t->OnVolume((*reinterpret_cast< int(*)>(_a[1]))); break;
        case 25: _t->OnAlbumArtChanged((*reinterpret_cast< const QString(*)>(_a[1]))); break;
        default: ;
        }
    } else if (_c == QMetaObject::IndexOfMethod) {
        int *result = reinterpret_cast<int *>(_a[0]);
        void **func = reinterpret_cast<void **>(_a[1]);
        {
            typedef void (VorbitalDlg::*_t)(int );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::numchannelsChanged)) {
                *result = 0;
                return;
            }
        }
        {
            typedef void (VorbitalDlg::*_t)(int );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::bitrateChanged)) {
                *result = 1;
                return;
            }
        }
        {
            typedef void (VorbitalDlg::*_t)(int );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::bitdepthChanged)) {
                *result = 2;
                return;
            }
        }
        {
            typedef void (VorbitalDlg::*_t)(int );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::samplerateChanged)) {
                *result = 3;
                return;
            }
        }
        {
            typedef void (VorbitalDlg::*_t)(int );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::timeChanged)) {
                *result = 4;
                return;
            }
        }
        {
            typedef void (VorbitalDlg::*_t)(int );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::volumeChanged)) {
                *result = 5;
                return;
            }
        }
        {
            typedef void (VorbitalDlg::*_t)(const QString & );
            if (*reinterpret_cast<_t *>(func) == static_cast<_t>(&VorbitalDlg::albumArtChanged)) {
                *result = 6;
                return;
            }
        }
    }
}

const QMetaObject VorbitalDlg::staticMetaObject = {
    { &QDialog::staticMetaObject, qt_meta_stringdata_VorbitalDlg.data,
      qt_meta_data_VorbitalDlg,  qt_static_metacall, Q_NULLPTR, Q_NULLPTR}
};


const QMetaObject *VorbitalDlg::metaObject() const
{
    return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : &staticMetaObject;
}

void *VorbitalDlg::qt_metacast(const char *_clname)
{
    if (!_clname) return Q_NULLPTR;
    if (!strcmp(_clname, qt_meta_stringdata_VorbitalDlg.stringdata0))
        return static_cast<void*>(const_cast< VorbitalDlg*>(this));
    return QDialog::qt_metacast(_clname);
}

int VorbitalDlg::qt_metacall(QMetaObject::Call _c, int _id, void **_a)
{
    _id = QDialog::qt_metacall(_c, _id, _a);
    if (_id < 0)
        return _id;
    if (_c == QMetaObject::InvokeMetaMethod) {
        if (_id < 26)
            qt_static_metacall(this, _c, _id, _a);
        _id -= 26;
    } else if (_c == QMetaObject::RegisterMethodArgumentMetaType) {
        if (_id < 26)
            *reinterpret_cast<int*>(_a[0]) = -1;
        _id -= 26;
    }
    return _id;
}

// SIGNAL 0
void VorbitalDlg::numchannelsChanged(int _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 0, _a);
}

// SIGNAL 1
void VorbitalDlg::bitrateChanged(int _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 1, _a);
}

// SIGNAL 2
void VorbitalDlg::bitdepthChanged(int _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 2, _a);
}

// SIGNAL 3
void VorbitalDlg::samplerateChanged(int _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 3, _a);
}

// SIGNAL 4
void VorbitalDlg::timeChanged(int _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 4, _a);
}

// SIGNAL 5
void VorbitalDlg::volumeChanged(int _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 5, _a);
}

// SIGNAL 6
void VorbitalDlg::albumArtChanged(const QString & _t1)
{
    void *_a[] = { Q_NULLPTR, const_cast<void*>(reinterpret_cast<const void*>(&_t1)) };
    QMetaObject::activate(this, &staticMetaObject, 6, _a);
}
QT_END_MOC_NAMESPACE
